### ISSUE TITLE
Skift fra SQLite til Postgres

### ISSUE THREAD

**Issue by AeselCSS** [CEM-KEA/whoknows#112]
Husk at tage api ned så vi ikke har brugere der ikke bliver flyttet med

**Comment by emilvn** [comment]
Måske der er noget på whoknows_variations database branch der kan hjælpe med denne opgave: https://github.com/who-knows-inc/whoknows_variations/tree/database_postgresql

Package vi måske kan bruge til at migrere og også at versionsstyre vores db og gøre rollbacks nemme: https://github.com/go-gormigrate/gormigrate

**Comment by AeselCSS** [comment]
### Husk:
- tests skal kører på en in memory sqlite3 db
- omskriv tests der omhandler forbindelse til db til at teste forbindelse til den reelle postgres db
- port indhold af existerende sqlite3 db til postgres (husk at tage api'et ned mens vi roder, så vi ikke ender med brugere der oprettes i sqlite3 uden at blive portet)
- implementer migrations med versioner (se tidligere kommentar fra @emilvn)
- fjern bruger fra seeder.go
- juster dockerfile på backend
- juster compose
- fjern *.db inkl. /legacy #127
