### ISSUE TITLE
Database filerne må ikke ligge på vores repository.

### ISSUE THREAD

**Issue by emilvn** [CEM-KEA/whoknows#127]
Siger sig selv.
Vi skal have lagt vores database op på vm'en på en anden måde.
Database filerne skal slettes fra vores backend kode og fra legacy koden.

**Comment by emilvn** [comment]
Giver måske mening at fikse i forbindelse med #112.

**Comment by emilvn** [comment]
@AeselCSS  Fikser du dette samtidig med #112 ?

**Comment by AeselCSS** [comment]
Ja de to bør fixes sammen for nemheds skyld
