### ISSUE TITLE
How are we DevOps?

### ISSUE THREAD

**Issue by emilvn** [CEM-KEA/whoknows#141]
# How are you DevOps?

**Type**: Group work

**Part of Mandatory II**

---

## The assignment

Inspired by the guest lecture start writing down arguments for why you are DevOps.

Also write down what keeps you from being fully DevOps while reflecting on why. 

https://github.com/who-knows-inc/KEA_DAT_DevOps_2024_Autumn/blob/main/00._Course_Material/02._Slides/08._Continuous_Deployment/02._devops.md

**Comment by emilvn** [comment]
# The Principles of Flow

* Make Work Visible. 
Alle tasks fremgår som issues på vores Github Projects kanban, som alle kan se. Automatisk genereret release notes, der dækker over hvad der er nyt. Obligatorisk peer review af PR gør at andre medlemmer af gruppen er med på ændringer.

* Limit Work in Progress
Vi har som udgangspunkt kun gang i 1 issue af gangen pr. gruppemedlem. Vi splitter features op i så små bidder (issues) som muligt.

* Reduce Batch Sizes
Vi splitter features op i så små bidder (issues) som muligt.

* Reduce the Number of Handoffs
Dette opnår vi ikke til fulde, da vi har obligatorisk peer review, hvilket betyder at vi altid vil have et handoff step for hvert issue. Og da vi stræber efter så små issues som muligt vil vi få mange små pull requests der skal reviewes og derfor også mange handoffs. Dog er disse pull requests meget små og simple og hurtige at reviewe.

* Continually Identify and Evaluate Constraints


* Eliminate Hardships and Waste in the Value Stream
Vi stræber efter at få automatiseret alle manuelle steps, og få reduceret tidsspild, ved at automatisere workflows, og rykke rundt på rækkefølgen af steps/jobs i vores CI/CD pipeline, sådan at vi får brugt tiden så optimalt som muligt.

**Comment by emilvn** [comment]
#  The Principles of *Feedback*

* See Problems as They Occur
Dette opnår vi gennem automatiserede tests af koden allerede ved Pull requests, så man opdager fejl inden de bliver merget til main. Desuden har vi Postman monitor som flere gange dagligt 

* Swarm and Solve Problems to Build New Knowledge

* Keep Pushing Quality Closer to the Source

* Enable Optimizing for Downstream Work Centers

**Comment by emilvn** [comment]
#  The Principles of *Continual Learning and Experimentation*

* Institutionalize the Improvement of Daily Work
Vi arbejder ikke dagligt på projektet. Men stræber efter at forbedre den måde vi arbejder sammen på. 

* Transform Local Discoveries into Global Improvements
Når vi opdager/finder nye smarte løsninger på ting, deler vi dem med hinanden, så vi alle kan få nytte af "opdagelsen".

* Inject Resilience Patterns into Our Daily Work

* Leaders Reinforce a Learning Culture
Vi har ikke rigtig nogen ledere, men arbejder med en meget åben tilgang til at vi alle er i en læringsprocess og ingen forventes at vide alt på forhånd.

**Comment by AeselCSS** [comment]
## The Principles of Flow

### Make Work Visible
Alle opgaver er organiseret som issues på vores GitHub Projects Kanban-tavle, hvilket sikrer gennemsigtighed for alle teammedlemmer. Automatiserede release-noter opsummerer nye funktioner og opdateringer, mens obligatoriske peer-reviews for pull requests holder hele teamet informeret om ændringer og involveret i udviklingsprocessen.

### Limit Work in Progress
Hvert teammedlem arbejder typisk kun på én opgave ad gangen. For at opretholde en effektiv fremgangsmåde opdeler vi funktioner i de mindst mulige opgaver (issues), hvilket hjælper os med at fokusere og undgå multitasking.

### Reduce Batch Sizes
Ved at opdele funktioner i mindre opgaver, søger vi at holde hver arbejdsmængde håndterbar, så det bliver lettere at afslutte, gennemgå og integrere.

### Reduce the Number of Handoffs
Selvom vores obligatoriske peer-review-proces naturligt introducerer handoffs, minimeres disse ved at sikre, at hver pull request (PR) er lille og let at gennemgå. Denne tilgang reducerer kompleksiteten af handoffs, selvom vi har hyppige, lette PR'er.

### Continually Identify and Evaluate Constraints
Vi vurderer løbende vores processer for flaskehalse eller tidskrævende manuelle opgaver. Når vi støder på disse, arbejder vi på at omarrangere eller optimere flowet for at reducere ventetider og forbedre effektiviteten, hvor det er muligt.

### Eliminate Hardships and Waste in the Value Stream
Vi stræber efter at automatisere alle gentagne trin med henblik på at reducere tidsspild og maksimere effektiviteten. Ved at automatisere workflows og optimere rækkefølgen af trin i vores CI/CD pipeline udnytter vi vores ressourcer bedst muligt og undgår unødvendige forsinkelser. 

## The Principles of Feedback

### See Problems as They Occur
Automatiserede tests på pull request-stadiet gør det muligt for os at fange fejl tidligt, inden de når main-branchen. Derudover kører Postman-monitoren flere gange dagligt på vores produktion, og sender os e-mails, hvis der opstår problemer, så vi hurtigt kan tage hånd om dem.

### Swarm and Solve Problems to Build New Knowledge 
Når der opstår hændelser, som f.eks. nedetid, informerer vi straks gruppen. Tilgængelige teammedlemmer samarbejder for at identificere grundårsagen og udvikle en løsning, hvilket styrker vores fælles læring og vidensdeling.

### Keep Pushing Quality Closer to the Source 
Vi tilstræber at løse problemer og sikre kvaliteten så tidligt som muligt, enten gennem grundige peer-reviews eller proaktiv overvågning i pipeline’en.

### Enable Optimizing for Downstream Work Centers 
Dette princip er ikke aktuelt for os, da vi ikke har downstream arbejdscentre.

## The Principles of Continual Learning and Experimentation

### Institutionalize the Improvement of Daily Work
Selvom vi ikke arbejder på projektet dagligt, søger vi løbende måder at forbedre vores samarbejde og workflows på, for at sikre en konstant fremgang i teamets dynamik og produktivitet.

### Transform Local Discoveries into Global Improvements
Når en af os finder en innovativ løsning eller effektivisering, deler vi den med teamet, så alle kan få gavn af disse indsigter og vores fælles viden vokser.

### Inject Resilience Patterns into Our Daily Work
Vores engagement i at lære af hændelser og forbedre vores processer hjælper os med at indbygge robusthed i vores workflow, så vi kan håndtere udfordringer mere effektivt over tid.

### Leaders Reinforce a Learning Culture
Uden formelle ledere arbejder vi med en samarbejdende tilgang, hvor alle medlemmer opfordres til at lære og udvikle sig. Vores tilgang anerkender, at ingen forventes at vide alt fra starten; vi er alle en del af en løbende læringsproces.
