### ISSUE TITLE
Indexing the database

### ISSUE THREAD

**Issue by AeselCSS** [CEM-KEA/whoknows#185]
# Indexing
Type: Group work

## The task
Create indexes where you see it fit on the database you are using.

This can be done in both relational and NoSQL databases.

## [Optional] Measure the performance boost
It would be interesting to measure the performance before and after the indexes.

This could also be evident by your Postman monitors depending on the thoroughness of the tests.

Keep this number and feel free to bring it up during the exam presentation.

**Comment by emilvn** [comment]
Vi gjorde dette da vi satte Gorm op
