### ISSUE TITLE
Vælg, og reflektér over branching strategier

### ISSUE THREAD

**Issue by emilvn** [CEM-KEA/whoknows#46]
Trunk based development

**Comment by AeselCSS** [comment]
![Image](https://github.com/user-attachments/assets/4aeaae2b-73f8-4155-b1c4-fd59b7b0faa8)

**Comment by emilvn** [comment]
Åbner denne igen, da vi mangler at samle det rigtigt til et dokument for at opfylde kravene for opgaven:

Document for the mandatory
Create a document for the mandatory that answers the following questions:

- What version control strategy did you choose and how did you actually do it / enforce it?

- Why did your group chose the one you did? Why did you not choose others?

- What advantages and disadvantages did you run into during the course?

Feel free to revise the document even after deadline with new insights during the course.

**Comment by emilvn** [comment]
https://studkea.sharepoint.com/:w:/s/TeamDevOpsstudiegruppe/EVWgm6M4rwdNpI-xMDYRAhkBkCXZoypgoE9L18DvNhNlWQ?e=bLns48
