### ISSUE TITLE
/api/logout

### ISSUE THREAD

**Issue by emilvn** [CEM-KEA/whoknows#83]
Vi skal have en handler til /api/logout, som invaliderer en JWT, som så skal kaldes når man logger ud i frontenden.

**Comment by emilvn** [comment]
@AeselCSS havde du lavet denne? Synes at huske du snakkede om at du havde lavet den sammen med noget andet.

**Comment by AeselCSS** [comment]
Ikke endnu

**Comment by emilvn** [comment]
Implementeret med pull request #118
